# Generated by Django 6.0.5 on 2026-08-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_razorpay_order_id_booking_razorpay_signature'),
        ('tourist', '0016_rename_price_tourpricing_group_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='infants',
        ),
        migrations.AddField(
            model_name='booking',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tourist.tourpricing'),
        ),
    ]
