# Generated by Django 6.0.5 on 2026-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_adults_remove_booking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
