# Generated by Django 6.0.5 on 2026-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_guide_attempt_booking_guide_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='declined_guides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
