# Generated by Django 4.2.24 on 2026-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('blog', 'Blog Listing'), ('tours', 'Tours'), ('about', 'About'), ('contact', 'Contact')], max_length=50, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
