# Generated by Django 6.0.5 on 2026-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['slot_position']},
        ),
        migrations.AlterModelOptions(
            name='importantinformation',
            options={'ordering': ['slot_position']},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ['slot_position']},
        ),
        migrations.AlterModelOptions(
            name='tourexclude',
            options={'ordering': ['slot_position']},
        ),
        migrations.AlterModelOptions(
            name='tourhighlight',
            options={'ordering': ['slot_position']},
        ),
        migrations.AlterModelOptions(
            name='tourinclude',
            options={'ordering': ['slot_position']},
        ),
        migrations.RemoveField(
            model_name='importantinformation',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourexclude',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourhighlight',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourinclude',
            name='tour',
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.amenity'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excludes',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.tourexclude'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.tourhighlight'),
        ),
        migrations.AddField(
            model_name='tour',
            name='important_information',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.importantinformation'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.tourinclude'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourexclude',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourexclude',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourhighlight',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourinclude',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourinclude',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TourAmenity',
        ),
    ]
