# Generated by Django 6.0.5 on 2026-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_alter_amenity_options_and_more'),
    ]

    operations = [
        
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'ordering': ['slot_position']},
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='end_time',
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='slot_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
