# Generated by Django 6.0.5 on 2026-06-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_alter_tourschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.CreateModel(
            name='TourPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='tourist.tour')),
            ],
        ),
    ]
