# Generated by Django 6.0.5 on 2026-06-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0006_alter_tour_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
    ]
