# Generated by Django 6.0.5 on 2026-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0007_remove_tour_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
