# Generated by Django 6.0.5 on 2026-08-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0008_alter_tour_city_alter_tour_country_alter_tour_state'),
        ('user', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='user.location'),
        ),
    ]
