# Generated by Django 6.0.5 on 2026-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0009_tour_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
