# Generated by Django 6.0.5 on 2026-08-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0010_tour_seo_description_tour_seo_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='state',
        ),
    ]
