# Generated by Django 6.0.5 on 2026-08-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0011_remove_tour_city_remove_tour_country_and_more'),
        ('user', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='user.location'),
        ),
    ]
