# Generated by Django 6.0.5 on 2026-08-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0013_alter_tour_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourschedule',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tourist.tour'),
        ),
    ]
