# Generated by Django 6.0.5 on 2026-08-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0014_alter_tourschedule_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourschedule',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tourist.tour'),
            preserve_default=False,
        ),
    ]
