# Generated by Django 6.0.5 on 2026-08-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0015_alter_tourschedule_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpricing',
            old_name='price',
            new_name='group_price',
        ),
        migrations.RemoveField(
            model_name='tourpricing',
            name='person_type',
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='group_members',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='group_type',
            field=models.CharField(choices=[('upto_9', 'Up to 9 members'), ('10_20', '10 - 20 members'), ('20_50', '20 - 50 members')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
