# Generated by Django 4.2.24 on 2026-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0017_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('slot_position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['slot_position'],
            },
        ),
    ]
