# Generated by Django 4.2.24 on 2026-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0018_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tourist.itinerary'),
        ),
    ]
