# Generated by Django 6.0.5 on 2026-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_country_remove_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide'), ('admin', 'Admin')], max_length=20),
        ),
    ]
