# Generated by Django 6.0.5 on 2026-09-07 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_registrationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(max_length=500)),
                ('aadhaar_front', models.ImageField(upload_to='guide_documents/aadhaar/')),
                ('aadhaar_back', models.ImageField(upload_to='guide_documents/aadhaar/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='guide_documents/certificates/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
