# Generated by Django 4.2.24 on 2026-10-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
