# Generated by Django 4.2.24 on 2026-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_location_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='architecture',
        ),
    ]
