# Generated by Django 4.2.24 on 2026-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_place_location_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='architecture',
            field=models.CharField(max_length=200),
        ),
    ]
