# Generated by Django 4.2.24 on 2026-10-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_location_architecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['state', 'district', 'city', 'architecture']},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('state', 'district', 'city', 'architecture')},
        ),
    ]
