# Generated by Django 6.0.5 on 2026-09-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_declined_guides'),
        ('rating', '0002_rating_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='booking.booking'),
        ),
    ]
